// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtcNbRRFkXphvQoI0N48HGK0l3VO-mA3U',
    appId: '1:29379866804:web:1d6456024d3d1f22dce7e1',
    messagingSenderId: '29379866804',
    projectId: 'charity-3e95f',
    authDomain: 'charity-3e95f.firebaseapp.com',
    storageBucket: 'charity-3e95f.appspot.com',
    measurementId: 'G-QXNK13FXNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArlpHo0fDT3Vv_ehl9I9YAiClfd6qC_gY',
    appId: '1:29379866804:android:fe545c592bf72499dce7e1',
    messagingSenderId: '29379866804',
    projectId: 'charity-3e95f',
    storageBucket: 'charity-3e95f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHIram77cCQROuZE1jncM5EanjrTeiM6o',
    appId: '1:29379866804:ios:de15d2a8bbd4423fdce7e1',
    messagingSenderId: '29379866804',
    projectId: 'charity-3e95f',
    storageBucket: 'charity-3e95f.appspot.com',
    iosClientId: '29379866804-r800bkjtr1vl2hht3uc7cd6s0jo1tdsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.oogway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHIram77cCQROuZE1jncM5EanjrTeiM6o',
    appId: '1:29379866804:ios:de15d2a8bbd4423fdce7e1',
    messagingSenderId: '29379866804',
    projectId: 'charity-3e95f',
    storageBucket: 'charity-3e95f.appspot.com',
    iosClientId: '29379866804-r800bkjtr1vl2hht3uc7cd6s0jo1tdsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.oogway',
  );
}
