name: oogway
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State Management
  riverpod: ^2.0.0-dev.4
  flutter_riverpod: ^2.0.0-dev.4

  # codegen
  chopper_generator: ^4.0.5
  build_runner: ^2.1.7
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  swagger_dart_code_generator: any
  smooth_page_indicator: ^1.0.0+2
  go_router: ^4.2.7
  firebase_core: ^1.20.1
  firebase_auth: ^3.6.3
  logger: ^1.1.0
  cloud_firestore: ^3.4.4
  recase: ^4.0.0
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^6.0.0
  after_layout: ^1.2.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
